node {
   def mvnHome
   stage('Preparation') { // for display purposes
      git branch: 'develop', credentialsId: '86a41f53-e4e7-4da3-a69a-6015f228baeb', url: 'https://github.com/darknite12/rms.git'
      mvnHome = tool 'm3'
      env.JAVA_HOME="${tool 'java8'}"
      env.DOCKER_HOST="unix://var/run/docker.sock"
      env.PATH="${env.JAVA_HOME}/bin:${env.PATH}"
   }
   
   stage('Unit Test') {
       dir('rms-donation-manager') {
           if (isUnix()) {
               sh "'${mvnHome}/bin/mvn' clean install"
           } else {
               bat(/"${mvnHome}\bin\mvn" clean install/)
           }
       }
   }
   
   stage('Build Docker Image') {
       dir('rms-donation-manager') {
           if (isUnix()) {
               sh "'${mvnHome}/bin/mvn' docker:build"
           } else {
               bat(/"${mvnHome}\bin\mvn" docker:build/)
           }
       }
    }
    
    stage('Integration Test') {
       dir('rms-donation-manager') {
           
       }
    }
}